### ISSUE TITLE
Parse HTTP body for every method

### ISSUE THREAD

**Issue by jbebe** [PatrickLouys/http#18]
Apparently this helper library is not able to receive PUT/DELETE/etc. parameters.
I solved the problem by writing this in the HttpRequest class at the bottom of the constructor:
```php
$streamParameters = [];
// merge stream (http body) with post parameters
if (self::isJsonString($this->inputStream)){
    // json
    $streamParameters = (array)json_decode($this->inputStream);
}
elseif ($this->inputStream){
    // url params
    $streamParameters = (array)self::httpParseQuery($this->inputStream);
}
$this->postParameters = array_merge($this->postParameters, $streamParameters);
```
I know this is not the nicest solution, but it still supports two encodings. If you have some time, please fix it.

[ModifiedRequest.zip](https://github.com/PatrickLouys/http/files/1042539/Request.zip)

**Comment by PatrickLouys** [comment]
PR's are always welcome
