### ISSUE TITLE
HttpResponse->setStatusCode() isn't sending correct status code.

### ISSUE THREAD

**Issue by ellisgl** [PatrickLouys/http#19]
$response->setContent('404 - Page not found');
$response->setStatusCode(404);
echo $response->getContent();

I get back Status Code 200, instead of 404.

**Comment by EcoJim** [comment]
Hi Ellisgl.  Have a look at the how to use examples again.  The code in your message is missing the bit that creates the HTTP headers, which will also let your browser know of the 404 status code.

Look out of the bit that goes like:
```
foreach($response->getHeaders() as $header) { 
     header($header);
}
```
