### ISSUE TITLE
Delete function

### ISSUE THREAD

**Issue by YELU369** [PatrickLouys/http#20]
How can I get id in the controller function?

['GET', '/leopard/view/{id:\d+}', ['App\Controllers\Admin\Leopard', 'view']],
['GET', '/leopard/edit/{id:\d+}', ['App\Controllers\Admin\Leopard', 'edit']],
['GET', '/leopard/delete/{id:\d+}', ['App\Controllers\Admin\Leopard', 'delete']],

**Comment by PatrickLouys** [comment]
This is only a HTTP package, not a routing library.
